version: '2'

services:
    roadrunner:
        build: ./application
        container_name: "roadrunner"
        env_file:
          - .env
        ports:
            - 8080:8080
        volumes:
            - ../:/var/www/app
